version: '3.8'

services:
  database:
    container_name: crypto-database
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
      POSTGRES_DB: crypto
    ports: 
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

